# Generated by Django 5.0.2 on 2024-03-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano_lancamento', models.IntegerField()),
                ('diretor', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
            ],
        ),
    ]
